// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwenbuxuttflbjoophdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3ZW5idXh1dHRmbGJqb29waGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0MjkxODAsImV4cCI6MjA1MjAwNTE4MH0.ZqRM50OjxaZX-Z64RhDk8CEctEPYxGv1XKYOZJN9OB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);